### ISSUE TITLE
sync-mht and stack

### ISSUE THREAD

**Issue by skogsbaer** [ekarayel/sync-mht#1]
I would like to install sync-mht using stack (https://github.com/commercialhaskell/stack). I tried to get stack up and running but failed because stack requires a `.cabal` file. But there is no `.cabal`, instead it seems that the `.cabal` file is generated from Haskell code. But I cannot generate the the `.cabal` file,

```
$ stack exec ghci configure.hs
Run from outside a project, using implicit global config
Using resolver: lts-3.9 from global config file: /Users/swehr/.stack/global/stack.yaml
GHCi, version 7.10.2: http://www.haskell.org/ghc/  :? for help

configure.hs:2:8:
    Could not find module ‘Configure.Helper’
    Use -v to see a list of the files searched for.
Failed, modules loaded: none.
```

So I'm somewhat stuck...

**Comment by ekarayel** [comment]
The error is due to missing submodules - e.g. you can clone with

```
git clone --recursive https://github.com/ekarayel/sync-mht.git
```

I just added a working stack.yaml file.

**Comment by skogsbaer** [comment]
Thanks!
