### ISSUE TITLE
Benchmarks fail to run on GHC 7.10.3

### ISSUE THREAD

**Issue by RyanGlScott** [ekarayel/sync-mht#3]
Steps to reproduce:

```
$ cabal get sync-mht
Unpacking to sync-mht-0.3.8.4/
$ cd sync-mht-0.3.8.4/
$ cabal bench
Package has never been configured. Configuring with default flags. If this
fails, please run configure manually.
Resolving dependencies...
Configuring sync-mht-0.3.8.4...
Preprocessing benchmark 'benchmarks' for sync-mht-0.3.8.4...
[1 of 1] Compiling Main             ( src/Benchmarks.hs, dist/build/benchmarks/benchmarks-tmp/Main.o )
Linking dist/build/benchmarks/benchmarks ...
Running 1 benchmarks...
Benchmark benchmarks: RUNNING...
benchmarks: user error (Pattern match failure in do expression at src/Benchmarks.hs:156:8-24)
Benchmark benchmarks: ERROR
```

See also https://github.com/iu-parfunc/sc-haskell/issues/7

**Comment by RyanGlScott** [comment]
Ah, never mind - this isn't `criterion`-based, so it's probably not meant to be run like this. Sorry for the noise.

**Comment by ekarayel** [comment]
Thanks for the info, Ryan. The benchmark test requires a network setup and port parameters.

If this is causing problems, I could make the benchmark suite a no-operation, if the required parameters are missing?

**Comment by RyanGlScott** [comment]
That would be acceptable, I think - or even spitting out a warning/error message explaining what the user needs to provide to `{cabal,stack} bench` to make it work.

Context: I'm running all of the benchmarks on Stackage by downloading them and running `stack bench` to gain benchmark results. This works pretty well for 90% of the cases, since most benchmarks use `criterion`, but there are corner cases like this one where you do need to provide input. Any guidance I can get in making it work would be appreciated!
